schema_version: 1

project:
  name: "nebulacast-app"
  slug: "nebulacast-app"
  description: "NebulaCast desktop and mobile applications."
  type: "app"
  version: 0.1.0
  status: active

organization:
  name: IncusLuminis

repository:
  visibility: "public"
  default_branch: main
  template: true

license:
  id: MIT

storage:
  code: github
  content: github
  media: external