import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { createLunarSnapshot, LUNAR_SOURCE } from "../sites/staging/shared/lunar.mjs";
import { onRequest } from "../functions/api/sun-moon.js";

const readJson = relative => JSON.parse(readFileSync(new URL(relative, import.meta.url), "utf8"));
const fixture = readJson("./fixtures/astronomy-consistency-v1.json");
const schema = readJson("../schemas/lunar-snapshot.v1.schema.json");

function source(relative) {
  return readFileSync(new URL(`../${relative}`, import.meta.url), "utf8");
}

function pickStaticMetadata(artifact) {
  const { version, schema, lunar_source, epoch, generated_at, source: producer, params, site, ownership, manifest } = artifact;
  return { version, schema, lunar_source, epoch, generated_at, source: producer, params, site, ownership, manifest };
}

async function apiAt(vector) {
  const NativeDate = globalThis.Date;
  const fixed = NativeDate.parse(vector.instant_utc);
  class FixedDate extends NativeDate {
    constructor(...args) { super(...(args.length ? args : [fixed])); }
    static now() { return fixed; }
  }
  globalThis.Date = FixedDate;
  try {
    const { lat, lon } = vector.observer;
    const query = new URLSearchParams({ lat: String(lat), lon: String(lon), days: "1", step_min: "60" });
    const response = await onRequest({ request: new Request(`https://baseline.test/api/sun-moon?${query}`) });
    assert.equal(response.status, 200);
    return response.json();
  } finally {
    globalThis.Date = NativeDate;
  }
}

test("fixture declares the versioned lunar schema, units, and owners", () => {
  assert.equal(fixture.schema, "astronomy-consistency.v1");
  assert.equal(fixture.contract.lunar_schema, "lunar-snapshot.v1");
  assert.equal(schema.properties.schema_version.const, fixture.contract.lunar_schema);
  assert.equal(schema.properties.lunar.properties.illuminated_percent.maximum, 100);
  assert.deepEqual(fixture.contract.lunar_units, {
    cycle_phase: "fraction",
    illuminated_fraction: "fraction",
    illuminated_percent: "percent",
    alt_deg: "degrees",
    az_deg: "degrees",
  });
  assert.equal(fixture.ownership.lunar_source, "frontend/astronomy/lunar.ts");
  assert.deepEqual(fixture.ownership.lunar_generated, [
    "sites/staging/shared/lunar.mjs",
    "functions/lib/lunar.js",
  ]);
});

test("fixed observer vectors reproduce canonical lunar snapshots", () => {
  for (const vector of fixture.vectors) {
    const snapshot = createLunarSnapshot({
      instant: new Date(vector.instant_utc),
      location: vector.observer,
    });
    assert.equal(snapshot.schema_version, fixture.contract.lunar_schema, vector.id);
    assert.equal(snapshot.source, fixture.contract.lunar_source, vector.id);
    assert.equal(snapshot.computed_at_utc, `${vector.instant_utc.slice(0, 19)}.000Z`, vector.id);
    assert.deepEqual(snapshot.location, {
      lat: vector.observer.lat,
      lon: vector.observer.lon,
      timezone: vector.observer.timezone,
    }, vector.id);
    assert.deepEqual(snapshot.lunar, vector.lunar, vector.id);
    assert.equal(snapshot.lunar.illuminated_percent, snapshot.lunar.illuminated_fraction * 100, vector.id);
    assert.ok(snapshot.lunar.cycle_phase >= 0 && snapshot.lunar.cycle_phase <= 1, vector.id);
    assert.ok(snapshot.lunar.illuminated_fraction >= 0 && snapshot.lunar.illuminated_fraction <= 1, vector.id);
    assert.ok(Object.isFrozen(snapshot), vector.id);
  }
});

test("authoritative and generated lunar sources retain explicit ownership markers", () => {
  const ts = source("frontend/astronomy/lunar.ts");
  const browserGenerated = source("sites/staging/shared/lunar.mjs");
  const functionGenerated = source("functions/lib/lunar.js");
  assert.match(ts, /LUNAR_SOURCE\s*=\s*['"]astronomy-engine@2\.1\.19['"]/);
  assert.match(ts, /schema_version:\s*['"]lunar-snapshot\.v1['"]/);
  assert.match(browserGenerated, /Generated by npm run build:lunar/);
  assert.match(browserGenerated, /lunar-snapshot\.v1/);
  assert.match(functionGenerated, /Generated by npm run build:lunar/);
  assert.match(functionGenerated, /astronomy-engine@2\.1\.19/);
  for (const relative of ["sites/staging/sky/core/sky.prepare.js", "sites/staging/weather/widgets/sun_moon/sun_moon.js", "sites/staging/hero/widget.js"]) {
    assert.match(source(relative), /createLunarSnapshot/);
  }
});

test("API vectors preserve sun_moon.v2 metadata and shared lunar semantics", async () => {
  for (const vector of fixture.vectors) {
    const data = await apiAt(vector);
    assert.equal(data.schema, fixture.contract.api_schema, vector.id);
    assert.equal(data.version, 2, vector.id);
    assert.equal(data.lunar_source, fixture.contract.lunar_source, vector.id);
    assert.equal(data.epoch, fixture.contract.api_epoch, vector.id);
    assert.equal(data.source, fixture.contract.api_source, vector.id);
    assert.deepEqual(data.params, vector.api.params, vector.id);
    assert.deepEqual(data.site, vector.api.site, vector.id);
    assert.deepEqual(data.window, vector.api.window, vector.id);
    assert.equal(data.frames.length, 25, vector.id);
    assert.deepEqual(data.frames[0], vector.api.first_frame, vector.id);
    assert.deepEqual(data.frames.at(-1), vector.api.last_frame, vector.id);
    for (const frame of [data.frames[0], data.frames.at(-1)]) {
      assert.ok(frame.moon.illum_pct >= 0 && frame.moon.illum_pct <= 100, vector.id);
      assert.ok(frame.moon.phase >= 0 && frame.moon.phase <= 1, vector.id);
      for (const body of [frame.sun, frame.moon]) for (const field of ["ra_deg", "dec_deg", "alt_deg", "az_deg"]) {
        assert.equal(typeof body[field], "number", `${vector.id} ${field}`);
      }
    }
  }
});

test("static sun_moon.v2 artifact keeps Warsaw ownership and first-frame baseline", () => {
  const artifact = readJson("../sites/staging/sky/data/sun_moon.json");
  assert.deepEqual(pickStaticMetadata(artifact), fixture.static_artifact.metadata);
  assert.equal(artifact.frames.length, fixture.static_artifact.frame_count);
  assert.deepEqual(artifact.frames[0], fixture.static_artifact.first_frame);
  assert.equal(artifact.ownership.kind, "static");
  assert.equal(artifact.ownership.location_id, "default-warsaw");
  assert.deepEqual(artifact.ownership.coordinates, { lat_deg: 52.2297, lon_deg: 21.0122 });
});
