import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

const options = {
  entryPoints: [fileURLToPath(new URL('../frontend/astronomy/lunar.ts', import.meta.url))],
  bundle: true, format: 'esm', platform: 'neutral', target: 'es2020',
  minify: true, legalComments: 'inline',
  banner: { js: '// Generated by npm run build:lunar. Edit frontend/astronomy/lunar.ts.' },
};
await Promise.all([
  build({ ...options, outfile: fileURLToPath(new URL('../sites/staging/shared/lunar.mjs', import.meta.url)) }),
  build({ ...options, outfile: fileURLToPath(new URL('../functions/lib/lunar.js', import.meta.url)) }),
]);
